train_batch_size: 256
test_batch_size: 256
device: cuda
train_file: data/train6000_en.tsv
test_file: data/val3000_en.tsv
model_name: distilroberta_lora_classifier
lr: 0.00001
dropout_rate: 0.5
max_epoch: 50